# Generated by Django 4.0.3 on 2022-04-02 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=50)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse')], default='House', max_length=50)),
                ('sqft', models.IntegerField()),
                ('open_house', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.URLField(blank=True)),
                ('photo_2', models.URLField(blank=True)),
                ('photo_3', models.URLField(blank=True)),
                ('photo_4', models.URLField(blank=True)),
                ('photo_5', models.URLField(blank=True)),
                ('photo_6', models.URLField(blank=True)),
                ('photo_7', models.URLField(blank=True)),
                ('photo_8', models.URLField(blank=True)),
                ('photo_9', models.URLField(blank=True)),
                ('photo_10', models.URLField(blank=True)),
                ('photo_11', models.URLField(blank=True)),
                ('photo_12', models.URLField(blank=True)),
                ('photo_13', models.URLField(blank=True)),
                ('photo_14', models.URLField(blank=True)),
                ('photo_15', models.URLField(blank=True)),
                ('photo_16', models.URLField(blank=True)),
                ('photo_17', models.URLField(blank=True)),
                ('photo_18', models.URLField(blank=True)),
                ('photo_19', models.URLField(blank=True)),
                ('photo_20', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realters.realtor')),
            ],
        ),
    ]
